theme: jekyll-theme-minimal
title: Alcino Cunha
logo: photo.jpg
description: "<a href=\"mailto:alcino@di.uminho.pt\">alcino@di.uminho.pt</a></br><a href=\"tel:+351253604444\">+351 253604444</a>"
show_downloads: false
